# The name of the tunnel to run
tunnel: whatsapp-agent-tunnel

# Path to the credentials file. Because this file is in the same
# directory as the config, we can just use its name.
credentials-file: 'C:\Users\username\path_to_project\whatsapp-fastapi-agent\.cloudflared\cred.json'

# Ingress rules for this tunnel
ingress:
  # Route traffic from your new subdomain to your local FastAPI server
  - hostname: whatsapp-agent.your_domain.com
    service: http://localhost:8000      # keep container port stable, does not read .env., so match with uvicorn port

  # A mandatory catch-all that returns a 404 for any other traffic
  - service: http_status:404
